docs/help.html, docs/program_schema.json, index.html, json/pkc_config.json, scripts/editor.js, styles/main.css
=> Added nav menu at top right and help file(s).

index.html, json/pkc_config.json, scripts/editor.js, styles/main.css
Add ability to edit and delete and existing talk, using the same modal as we used for creating a new talk. If the id is empty, then we're adding a new talk, but if the id is non-empty, then we are editing or deleting an existing talk.
=> Kevin edit talks

ajax.php, index.html
Two bugs:
1. there was a spurious < in index.html.
2. if the database was empty, then trying to edit an existing program would fail.
=> Minor bug fixes.

index.html, styles/main.css
A simpler form for the template, and switch to h3 instead of h4 for the session title.
=> Kevin simple template

index.html, json/ec_config.json, styles/main.css
There are now three templates to start from, and they all contain boilerplate for session titles, banquet, etc.
=> Better templates to start a new program from.

index.html, scripts/editor.js, styles/main.css
In the process of creating a new program, we now ask for the name, insert that into progData.name, and store that in the database. After this when the user asks to edit an existing program, they will see what they selected as a name.
=> Ask user for name of program

index.html, scripts/editor.js
This introduces a modal to upload papers from websubrev, so we can share the UI from both the startup and the menu item. Unfortunately there are still some bugs here - it replaces the existing list of papers rather than adds to them. In a subsequent fix I will detect duplicates and merge into the existing unscheduled talks.
=> Ability to upload papers.

index.html, styles/main.css
Remove extraneous warning text, fix text alignment, fix font size for author list
=> Quick fixes

styles/main.css
Remove red edit button, fade out background of talks upon hover to allow for visibility of edit talk pencil
=> tl;dr fixed the terrible red edit button

index.html, scripts/editor.js, styles/main.css
The form validation warnings are shown in inconsistent style, but this illustrates several ways to do it.
=> Various pieces for validation and css to show invalid fields.

index.html, scripts/editor.js, styles/main.css
We still need a UI for progress on matching papers to DOIs, but at least now the links show up.
=> Update to documentation and links for papers in the program.

index.html, scripts/editor.js, styles/main.css
Add "Save as" capability.
Change pencil icon to have better contrast.
Change list of existing programss to have better contrast.
=> Kevin touchup

ajax.php, index.html, scripts/editor.js, styles/main.css
This adds authentication to the app using PHP sessions and an external method to verify the username/password combination. The actual code to verify the username/password is not in this pull request, and can be replaced with something appropriate to the installation.
=> Add authentication

ajax.php, index.html, scripts/editor.js
This makes several changes:
1. the ability for a user to delete their own programs.
2. the ability to create two programs with the same name (remove a unique index).
3. the 'id' field in the database is propagated to database_id in the progData.
=> Implement delete, and track database_id in progData.

scripts/editor.js
This should fix issue #126 by disabling the menus when they have the class 'disabled'.
=> Disable javascript in menus.

README.md, index.html, pdf/program.php, pdf/templates/program.tpl, scripts/editor.js
This introduces new dependencies for the twig PHP template engine (version >=1.0) and the mpdf PHP library for generating PDF. Note that these are not included in the repository, but must be installed with composer.
=> PDF printing added.

index.html, scripts/editor.js, styles/main.css
This addresses issue #117 with considerable flexibility by allowing the user to delete, add, and edit category names.
=> Delete, add, and edit categories

index.html, scripts/editor.js, styles/main.css
This addresses issues #120 and #131  by allowing the user to edit some fields in progData.
=>  Add ability to edit metadata on a program.

index.html, scripts/editor.js
A simple change with a Handlebars helper will show dates as 2018-08-21 (Tuesday) instead of just 2018-08-21. This is easy because we already have a dependency on moment.
=> Format dates with the day of the week.

scripts/editor.js
This should allow the user to delete the paperUrl.
=> Allow user to delete paperUrl

index.html, scripts/editor.js, styles/main.css
Also fix a bug in findObj and change styling on instructions for the editor
to allow more space on screen.
=> Add ability to import from Cryptodb for CHES and FSE.

index.html, scripts/editor.js, styles/main.css
This is a really really really old set of changes.
=> These changes are mostly to fix broken edit buttons.

index.html, styles/bootstrap.flatly.css, styles/main.css
DOM for navbar mostly working, just ugly in places
=> Bootstrap4 migration

index.html, scripts/editor.js
This puts ToSC and TCHES into categories for the volume.
=> Improve handling of volumes from TOSC and TCHES.

styles/main.css
This simple change allows us to edit talks in the uncategorized category. We only disable hover on the immediate child of #category-0 (the category).
=> Bs4 migration

index.html
=> Last of the modals

index.html, scripts/editor.js
=> Updated documentation for user when deleting a single session

docs/program_schema.json, index.html, json/virtual_5day.json, scripts/editor.js
Add a timezone to config
Add a template for 5-day virtual conference.
Add support for import with pubkey in talks.
=> A few changes for a virtual conference.

scripts/editor.js
This should leave an existing session id alone. #226
=> Fix for issue #226

docs/program_schema.json, index.html, scripts/editor.js, styles/main.css
pretty sure this is tested and working but I'd feel better doing some testing together
=> Added additional note field for talks

index.html, scripts/editor.js, styles/main.css
This has been hanging around for a while.
=> Allow editing on timezones.

index.html, scripts/editor.js
=> talkNote removal.

ajax.php
Now ../auth has both the server and client in the repository.
=> The auth repositories were merged

docs/program_schema.json, index.html, json/virtual_5day.json, pdf/templates/program.tpl, scripts/editor.js
A few other fixes:
1. the schema has better documentation
2. Remove Location: and Chair: from the default template for PDF
3. bump the version of scripts/editor.js in index.html
=> Use deterministic ordering on exported JSON.

index.html, scripts/editor.js
This allows the user to edit the abstract.
=> Add ability to edit abstract. See #45

index.html, scripts/editor.js
Most of this is straight forward. Some of it is not.
=> Now it works.
